### ISSUE TITLE
The parameter specified in the request is not valid

### ISSUE THREAD

**Issue by gaozhangmin** [kishikawakatsumi/SMBClient#107]
I ran the Example, connect with my local smb server.
![image](https://github.com/user-attachments/assets/35821e68-ca82-499f-b901-dfb2246096cf)

**Comment by kishikawakatsumi** [comment]
Please tell us about the settings of your SMB server. How can I reproduce the problem in my environment?

**Comment by gaozhangmin** [comment]
> Please tell us about the settings of your SMB server. How can I reproduce the problem in my environment?

Windows Version：
![image](https://github.com/user-attachments/assets/c0887b95-424d-4f86-96c1-9c672547b37a)

SMB Conf:
![image](https://github.com/user-attachments/assets/6e6baf4f-fdd3-4d15-857e-df8c57d11b4d)

**Comment by kishikawakatsumi** [comment]
What kind of operation causes the error? Is it when you log in?
Can you debug it yourself and get more information? Or can you send the contents of the packet capture?

I need more information to reproduce the problem in my environment.

**Comment by gaozhangmin** [comment]
This is the packet returned from smb server
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/4e338663-6953-4bb9-b091-d5368a739148">

**Comment by gaozhangmin** [comment]
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/21e8b343-34e9-4fca-8d93-03dd2d3e961e

**Comment by kishikawakatsumi** [comment]
It's hard to imagine that Windows 10 doesn't support Multi Credits, and it looks like it does in the SMB conf you shared. That's probably not the cause. Can you share the Negotiate Response capture and the complete Tree Connect Request capture?

**Comment by gaozhangmin** [comment]
<img width="548" alt="image" src="https://github.com/user-attachments/assets/997ca029-c4bd-4d17-a038-22e45d719db5">
<img width="806" alt="image" src="https://github.com/user-attachments/assets/2872be5f-75fc-4384-8f9b-ab9b703749fd">

**Comment by kishikawakatsumi** [comment]
It is failing to obtain the shared list. Are you able to connect from other clients or PCs without any problems? If so, could you share the packet capture files for when you are able to connect correctly and for when you are unable to connect?

**Comment by gaozhangmin** [comment]
Success packet 
<img width="633" alt="image" src="https://github.com/user-attachments/assets/1638b3fe-8539-4176-95eb-7098b357d900">
<img width="947" alt="image" src="https://github.com/user-attachments/assets/6e4c0c0e-10cd-4aa3-ae3b-724260aaf682">

**Comment by kishikawakatsumi** [comment]
Perhaps the server does not support packet signing. Can you show me the capture of the Negotiate Response?

**Comment by kishikawakatsumi** [comment]
Closed due to no response. Feel free to reopen if you have additional information. Thank you for reporting.
