### ISSUE TITLE
this parameter specified in the request is not valid

### ISSUE THREAD

**Issue by chinamingsss** [kishikawakatsumi/SMBClient#111]
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID. inputModality = Keyboard, inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations

**Comment by kishikawakatsumi** [comment]
We do not have enough information to investigate. Please describe the problem in detail and tell us how to reproduce it here.

**Comment by kishikawakatsumi** [comment]
Closed due to no response. Feel free to reopen if you have additional information.
