### ISSUE TITLE
The parameter specified in the request is not valid.

### ISSUE THREAD

**Issue by chinamingsss** [kishikawakatsumi/SMBClient#112]
SMB2 Header
  ProtocolId: 0xfe534d42
  Header Length: 64
  Credit Charge: 1
  NT Status: SUCCESS (0x00000000)
  Command: SESSION_SETUP (1)
  Credits granted: 1
  Flags: 0x00000009 (Response, Signing)
  Chain Offset: 0
  Message ID: 2
  Process Id: 0x00000000
  Tree Id: 0x00000000
  Session Id: 0x000110002800007d
  Signature: c4163b965f071ece778f83989e9dc525
Session Setup Response (0x01)
  StructureSize: 9
  Session Flags: 0x0000
  Blob Offset: 72
  Blob Length: 0
  Security Blob: 
The parameter specified in the request is not valid.

**Comment by kishikawakatsumi** [comment]
We do not have enough information to investigate. Please describe the problem in detail and tell us how to reproduce it here.

**Comment by kishikawakatsumi** [comment]
Closed due to no response. Feel free to reopen if you have additional information.
