### ISSUE TITLE
Connection Fail on Apple AirMac Time Capsule

### ISSUE THREAD

**Issue by noppefoxwolf** [kishikawakatsumi/SMBClient#152]
Apple AirMac Time Capsule supports SMB 1.0 connection.
AirMac always returns 35 byte header.

![CleanShot 2024-09-25 at 01 57 48@2x](https://github.com/user-attachments/assets/8ab67be2-ffe8-46bc-baab-cbfd1e3482d5)

**Comment by kishikawakatsumi** [comment]
This library does not support SMB1 and will not support SMB1 in the near future. The reason is that SMB1 and SMB2 are　different incompatible protocols with completely different packet structures.
