### ISSUE TITLE
NWError 54 - Connection reset by peer

### ISSUE THREAD

**Issue by PLKHawaR** [kishikawakatsumi/SMBClient#177]
When I manually add a server and then restart the Example app, I am unable to connect to the recently added server, and it displays the error "Connection reset by peer." I have encountered this issue multiple times. Additionally, when I try to add a server from the discovered list by entering the username and password, it shows an error and fails to add the server.

**Comment by kishikawakatsumi** [comment]
Please provide us with the missing information to investigate. Does the server you are trying to connect to support the SMB2 protocol, or is it a Windows File share? Or is it a Mac? Or is it a NAS? Are there any other successful connections in your environment? How can I reproduce your problem in my environment?

**Comment by PLKHawaR** [comment]
My server is a NAS. When I try to connect by selecting the discovered NAS server and entering the username and password, it shows an error.

**Comment by kishikawakatsumi** [comment]
Is there any way to reproduce the problem here?

According to another post [here](https://github.com/kishikawakatsumi/SMBClient/issues/178), you are able to log in using the library, but is it the same NAS?

**Comment by PLKHawaR** [comment]
i am talking about ur example app u provide, but it works in my case.
