### ISSUE TITLE
SMBClient Fails to Access Specific Directory

### ISSUE THREAD

**Issue by PLKHawaR** [kishikawakatsumi/SMBClient#178]
When I use client.listShares(), it works fine, but when I try accessing a specific directory, it fails and shows an error. I expect that I don't need to provide the full path like smb://111.11.11.11:username@password/media since the connection is already established, and only the relative path should be required.
And what the url if we don't have IP Address like smb://NAS i am receiving this while discover smb servers then how can i login it ?

**Comment by kishikawakatsumi** [comment]
What code is causing the problem? Please tell us what code you are writing.

**Comment by PLKHawaR** [comment]
Here is the code:
let client = SMBClient(host: "192.168.**.**")
try await client.login(username: "media", password: "Abc")
let shares = try await client.listShares()
print("Available shares: \(shares.map { $0.name })")
let files = try await client.listDirectory(path: "media/Videos")
print("Result: \(files)")
        
 I successfully retrieved the available shares, but when I try to list the directory, I encounter the error: 'Error connecting to SMB: Network Name Deleted.

**Comment by kishikawakatsumi** [comment]
@PLKHawaR The SMB2 protocol requires a connection to a shared drive before any file operations. `listShares()` returns a list of shared drives. Connect to the shared drive by passing to the `connectShare()` function the name of a shared drive to which you have permission (one of the names returned by `listShares()`).

For example, the following example connects to a shared drive named `Public` and displays the files in its root directory.

```swift
import SMBClient

let client = SMBClient(host: "198.51.100.50")

try await client.login(username: "alice", password: "secret")
try await client.connectShare("Public")

let files = try await client.listDirectory("")
print(files.map { $0.fileName })
```

See also:
https://github.com/kishikawakatsumi/SMBClient?tab=readme-ov-file#usage
