### ISSUE TITLE
The parameter specified in the request is not valid.

### ISSUE THREAD

**Issue by isaced** [kishikawakatsumi/SMBClient#93]
```swift
...
client.listShares()                  // ["a", "b", ...] ok.
client.connectShare("a")             // ok.
client.listDirectory("")             // ["d", "e", ...] ok.
client.listDirectory("/d")           // error log -> "The parameter specified in the request is not valid."
```

Using AMSMB2 works normally. Switching to SMBClient causes this problem. (and this problem only occurs in some SMB source services)

> SMBClient v0.1.1
> iOS v17.4

**Comment by kishikawakatsumi** [comment]
This is the expected correct behavior as per the SMB2 protocol specification: the path given to Create Request must be relative to the share.

https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/e8fb45c1-a03d-44ca-b7ae-47385cfd7997

https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/8c61e928-9242-44ed-96a0-98d1032d0d39


AMSMB2 handles this by removing the preceding and following slashes before sending the request.


https://github.com/amosavian/AMSMB2/blob/77156f4c8794fdb41e36c3e2ccdc153e08cbca22/AMSMB2/Extensions.swift#L227-L229


I will consider whether to do the same for this library. My opinion is that I don't like libraries to do too much extra processing.


In the meantime, you can do the same for paths as the AMSMB2 as a simple solution.

```swift
extension String {
    var canonical: String {
        trimmingCharacters(in: .init(charactersIn: "/\\"))
    }
}
```
